import { cleanup, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { api } from '../api/endpoints';
import { PublicContentPage } from '../pages/public';

afterEach(cleanup);
describe('contenido público tipado', () => {
  it('muestra loading mientras carga contenido', () => { vi.spyOn(api, 'publicContent').mockReturnValueOnce(new Promise(() => {})); render(<PublicContentPage title="Noticias" />); expect(screen.getByRole('status')).toHaveTextContent('Cargando informacion...'); });
  it('muestra noticias y su estado vacío', async () => { vi.spyOn(api, 'publicContent').mockResolvedValueOnce({ ok: true, data: [{ id: 1, uuid: 'n', slug: 'noticia', title: 'Nueva atención', summary: 'Resumen', published_at: '2026-07-01T12:00:00Z' }] }); render(<PublicContentPage title="Noticias" />); expect(await screen.findByText('Nueva atención')).toBeInTheDocument(); vi.spyOn(api, 'publicContent').mockResolvedValueOnce({ ok: true, data: [] }); render(<PublicContentPage title="Noticias" />); expect(await screen.findByText('No hay noticias publicadas')).toBeInTheDocument(); });
  it('muestra avisos y su estado vacío', async () => { vi.spyOn(api, 'publicContent').mockResolvedValueOnce({ ok: true, data: [{ id: 2, uuid: 'a', title: 'Corte de tránsito', body_html: '<p>Información importante</p>', notice_type: 'warning', start_at: '2026-07-01T12:00:00Z', end_at: '2026-07-02T12:00:00Z' }] }); render(<PublicContentPage title="Avisos" />); expect(await screen.findByText('Corte de tránsito')).toBeInTheDocument(); vi.spyOn(api, 'publicContent').mockResolvedValueOnce({ ok: true, data: [] }); render(<PublicContentPage title="Avisos" />); expect(await screen.findByText('No hay avisos vigentes')).toBeInTheDocument(); });
  it('muestra calendario, vacío y error', async () => { vi.spyOn(api, 'publicContent').mockResolvedValueOnce({ ok: true, data: [{ id: 3, uuid: 'c', title: 'Sesión pública', description: 'Actividad municipal', start_at: '2026-07-01T12:00:00Z', end_at: '2026-07-01T13:00:00Z', location: 'Municipalidad', status: 'active' }] }); render(<PublicContentPage title="Calendario" />); expect(await screen.findByText('Sesión pública')).toBeInTheDocument(); vi.spyOn(api, 'publicContent').mockResolvedValueOnce({ ok: true, data: [] }); render(<PublicContentPage title="Calendario" />); expect(await screen.findByText('No hay actividades programadas')).toBeInTheDocument(); vi.spyOn(api, 'publicContent').mockRejectedValueOnce(new Error('Error de contenido')); render(<PublicContentPage title="Calendario" />); await waitFor(() => expect(screen.getByText('Error de contenido')).toBeInTheDocument()); });
});
