const findDocument = async (client, id, lock = false) => (await client.query(`SELECT d.*,s.code AS status FROM documents d JOIN document_statuses s ON s.id=d.status_id WHERE d.id=$1 AND d.deleted_at IS NULL${lock ? ' FOR UPDATE' : ''}`, [id])).rows[0] || null;
const activeUser = async (client, id) => (await client.query("SELECT id FROM users WHERE id=$1 AND status='active' AND deleted_at IS NULL", [id])).rows[0] || null;
const createRequest = async (client, data) => (await client.query(`INSERT INTO document_review_requests (document_id,requested_by,reviewer_user_id,review_round,instructions,due_at) VALUES ($1,$2,$3,(SELECT COALESCE(MAX(review_round),0)+1 FROM document_review_requests WHERE document_id=$1),$4,$5) RETURNING *`, [data.documentId, data.requestedBy, data.reviewerId, data.instructions || null, data.dueAt || null])).rows[0];
const setStatus = (client, documentId, code) => client.query('UPDATE documents SET status_id=(SELECT id FROM document_statuses WHERE code=$2),updated_at=now() WHERE id=$1', [documentId, code]);
const findRequest = async (client, id, lock = false) => (await client.query(`SELECT * FROM document_review_requests WHERE id=$1${lock ? ' FOR UPDATE' : ''}`, [id])).rows[0] || null;
const createResponse = async (client, data) => (await client.query('INSERT INTO document_review_responses (review_request_id,reviewer_user_id,decision,observations,requires_changes) VALUES ($1,$2,$3,$4,$5) RETURNING *', [data.reviewId, data.reviewerId, data.decision, data.observations || null, data.requiresChanges])).rows[0];
const updateRequest = (client, id, status) => client.query('UPDATE document_review_requests SET status=$2,updated_at=now() WHERE id=$1', [id, status]);
const list = async (client, documentId) => (await client.query(`SELECT r.*,u.full_name AS reviewer_name,rr.decision,rr.observations,rr.requires_changes,rr.responded_at FROM document_review_requests r JOIN users u ON u.id=r.reviewer_user_id LEFT JOIN LATERAL (SELECT * FROM document_review_responses WHERE review_request_id=r.id ORDER BY created_at DESC LIMIT 1) rr ON true WHERE r.document_id=$1 ORDER BY r.created_at DESC`, [documentId])).rows;
module.exports = { findDocument, activeUser, createRequest, setStatus, findRequest, createResponse, updateRequest, list };
