const { transaction } = require('../../database/transaction');
const { query } = require('../../database/pool');
const { AppError } = require('../../shared/errors');
const audit = require('../../shared/audit');
const repository = require('./repository');
function documentAllowed(document, actor) { if (!document) throw new AppError(404, 'DOCUMENT_NOT_FOUND', 'Documento no encontrado'); if (document.confidentiality_level === 'secret' && document.owner_user_id !== actor.id) throw new AppError(403, 'FORBIDDEN', 'No autorizado para este documento'); }
async function submit(documentId, data, actor, context) { return transaction(async (client) => { const document = await repository.findDocument(client, documentId, true); documentAllowed(document, actor); if (!document.current_version_id) throw new AppError(409, 'CURRENT_VERSION_REQUIRED', 'El documento debe tener una versión vigente'); if (data.reviewer_user_id === actor.id) throw new AppError(400, 'SELF_REVIEW_NOT_ALLOWED', 'No puede enviarse una revisión a sí mismo'); if (!await repository.activeUser(client, data.reviewer_user_id)) throw new AppError(400, 'REVIEWER_NOT_FOUND', 'El revisor no está activo'); if (['signed', 'published', 'archived', 'cancelled'].includes(document.status)) throw new AppError(409, 'DOCUMENT_NOT_REVIEWABLE', 'El documento no admite revisión'); const review = await repository.createRequest(client, { documentId, requestedBy: actor.id, reviewerId: data.reviewer_user_id, instructions: data.instructions, dueAt: data.due_at }); await repository.setStatus(client, documentId, 'in_revision'); await audit.record(client, { eventName: 'document_review_requested', moduleCode: 'document_reviews', entityType: 'document', entityId: documentId, actor, ipAddress: context.ip, payload: { review_id: review.id, reviewer_user_id: data.reviewer_user_id, review_round: review.review_round } }); return review; }); }
async function reply(reviewId, data, actor, context) { return transaction(async (client) => { const review = await repository.findRequest(client, reviewId, true); if (!review) throw new AppError(404, 'REVIEW_NOT_FOUND', 'Solicitud de revisión no encontrada');     if (Number(review.reviewer_user_id) !== actor.id) throw new AppError(403, 'FORBIDDEN', 'Solo puede responder el revisor asignado'); if (!['pending', 'in_review'].includes(review.status)) throw new AppError(409, 'REVIEW_ALREADY_CLOSED', 'La revisión ya fue respondida'); const decision = data.decision === 'changes_required' ? 'changes_requested' : data.decision; const response = await repository.createResponse(client, { reviewId, reviewerId: actor.id, decision, observations: data.observations, requiresChanges: decision === 'changes_requested' || decision === 'needs_clarification' }); const requestStatus = decision === 'approved' ? 'approved' : 'rejected'; await repository.updateRequest(client, reviewId, requestStatus); await repository.setStatus(client, review.document_id, 'draft'); await audit.record(client, { eventName: 'document_review_replied', moduleCode: 'document_reviews', entityType: 'document', entityId: review.document_id, actor, ipAddress: context.ip, payload: { review_id: reviewId, decision } }); return response; }); }
async function list(documentId, actor) { const document = await repository.findDocument({ query }, documentId); documentAllowed(document, actor); return repository.list({ query }, documentId); }
module.exports = { submit, reply, list };
