const crypto = require('crypto');
const { transaction } = require('../../database/transaction');
const { query } = require('../../database/pool');
const { AppError } = require('../../shared/errors');
const audit = require('../../shared/audit');
const repository = require('./repository');
function allowed(document, actor) { if (!document) throw new AppError(404, 'DOCUMENT_NOT_FOUND', 'Documento no encontrado'); if (document.confidentiality_level === 'secret' && document.owner_user_id !== actor.id) throw new AppError(403, 'FORBIDDEN', 'No autorizado para este documento'); }
async function sign(documentId, data, actor, context) { return transaction(async (client) => { const document = await repository.findDocument(client, documentId, true); allowed(document, actor); if (document.status !== 'approved') throw new AppError(409, 'DOCUMENT_NOT_READY_FOR_SIGNATURE', 'El documento debe estar aprobado antes de firmar'); if (await repository.incompleteApprovals(client, documentId) !== 0) throw new AppError(409, 'APPROVALS_INCOMPLETE', 'Existen aprobaciones pendientes o rechazadas'); const profile = await repository.findProfile(client, data.signature_profile_id, actor.id); if (!profile) throw new AppError(400, 'SIGNATURE_PROFILE_NOT_FOUND', 'El perfil de firma simulada no pertenece al usuario'); const signedAt = new Date().toISOString(); const signatureHash = crypto.createHash('sha256').update(`${document.uuid}:${document.current_version_id}:${profile.id}:${actor.id}:${signedAt}`).digest('hex'); const signature = await repository.create(client, { documentId, signerId: actor.id, profileId: profile.id, mode: data.signature_mode, hash: signatureHash }); await repository.setStatus(client, documentId); await audit.record(client, { eventName: 'document_signed_simulated', moduleCode: 'document_signatures', entityType: 'document', entityId: documentId, actor, ipAddress: context.ip, payload: { signature_id: signature.id, signature_profile_id: profile.id, signature_hash: signatureHash } }); return signature; }); }
async function list(documentId, actor) { const document = await repository.findDocument({ query }, documentId); allowed(document, actor); return repository.list({ query }, documentId); }
module.exports = { sign, list };
