import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import { RequireActor } from '../auth/require-actor';
import { RequireAuth } from '../auth/require-auth';
import { RequirePermission } from '../auth/require-permission';
import { AdminLayout, CitizenPortalLayout, IntranetLayout, PublicLayout } from '../components/layout';
import { catalogByRoute, type Screen } from '../config/screen-catalog';
import { ExternalEntitiesPage, ProfilePage, DashboardPage, DocumentsListPage, DocumentCreatePage, DocumentDetailPage, DocumentVersionsPage, ReviewsPage, ApprovalsPage, SignaturePage, ExpedientsListPage, ExpedientDetailPage, CorrespondenceListPage, CorrespondenceCreatePage, UsersPage, RolesPage, DepartmentsPage, DocumentTypesPage, ProcedureTypesPage, ReportsPage, OirsManagementPage } from '../pages/intranet';
import { LoginPage, NotificationsPage, OirsPage, RequestFormPage, RecoverPage, CitizenRequestsPage } from '../pages/portal';
import { HomePage, ProcedureDetailPage, ProceduresPage, PublicContentPage } from '../pages/public';
import { NotFoundPage } from '../pages/shared';

const screen = (route: string) => catalogByRoute.get(route)!;
function Protected({ item, actor, children }: { item: Screen; actor: 'citizen' | 'internal'; children: React.ReactNode }) { return <RequireAuth><RequireActor actor={actor}><RequirePermission permission={item.required_permissions[0]}>{children}</RequirePermission></RequireActor></RequireAuth>; }


export function AppRouter() { return <BrowserRouter><Routes>
  <Route element={<PublicLayout/>}><Route index element={<HomePage/>}/><Route path="tramites" element={<ProceduresPage/>}/><Route path="tramites/:procedureId" element={<ProcedureDetailPage/>}/><Route path="noticias" element={<PublicContentPage title="Noticias"/>}/><Route path="avisos" element={<PublicContentPage title="Avisos"/>}/><Route path="calendario" element={<PublicContentPage title="Calendario"/>}/><Route path="oirs" element={<OirsPage/>}/></Route>
  <Route path="login" element={<LoginPage actor="citizen"/>}/><Route path="intranet/login" element={<LoginPage actor="internal"/>}/><Route path="recover" element={<RecoverPage />}/>
  <Route path="portal" element={<Protected item={screen('/portal/requests')} actor="citizen"><CitizenPortalLayout/></Protected>}><Route index element={<CitizenRequestsPage />}/><Route path="requests" element={<CitizenRequestsPage />}/><Route path="requests/new/:procedureId" element={<RequestFormPage/>}/><Route path="requests/:requestId" element={<CitizenRequestsPage />}/><Route path="oirs" element={<OirsManagementPage />}/><Route path="oirs/:caseId" element={<OirsManagementPage />}/><Route path="notifications" element={<NotificationsPage/>}/><Route path="profile" element={<CitizenRequestsPage />}/></Route>
  <Route path="intranet" element={<Protected item={screen('/intranet')} actor="internal"><IntranetLayout/></Protected>}><Route index element={<DashboardPage />}/><Route path="profile" element={<ProfilePage />}/><Route path="documents" element={<DocumentsListPage />}/><Route path="documents/new" element={<DocumentCreatePage />}/><Route path="documents/:documentId" element={<DocumentDetailPage />}/><Route path="documents/:documentId/versions" element={<DocumentVersionsPage />}/><Route path="documents/:documentId/signature" element={<SignaturePage />}/><Route path="reviews" element={<ReviewsPage />}/><Route path="approvals" element={<ApprovalsPage />}/><Route path="expedients" element={<ExpedientsListPage />}/><Route path="expedients/:expedientId" element={<ExpedientDetailPage />}/><Route path="correspondence" element={<CorrespondenceListPage />}/><Route path="correspondence/new" element={<CorrespondenceCreatePage />}/><Route path="correspondence/:correspondenceId" element={<CorrespondenceListPage />}/><Route path="oirs" element={<OirsManagementPage />}/><Route path="oirs/:caseId" element={<OirsManagementPage />}/><Route path="notifications" element={<NotificationsPage/>}/><Route path="reports" element={<ReportsPage />}/></Route>
  <Route path="intranet/admin" element={<Protected item={screen('/intranet/admin/users')} actor="internal"><AdminLayout/></Protected>}><Route path="users" element={<UsersPage />}/><Route path="roles" element={<RolesPage />}/><Route path="departments" element={<DepartmentsPage />}/><Route path="document-types" element={<DocumentTypesPage />}/><Route path="procedure-types" element={<ProcedureTypesPage />}/><Route path="external-entities" element={<ExternalEntitiesPage/>}/><Route path="public-content" element={<PublicContentPage title="Contenido publico"/>}/></Route>
  <Route path="forbidden" element={<PublicContentPage title="Acceso restringido"/>}/><Route path="*" element={<NotFoundPage/>}/><Route path="notifications" element={<Navigate to="/portal/notifications" replace/>}/>
</Routes></BrowserRouter>; }
