import { Link, NavLink, Outlet } from 'react-router-dom';
import { useAuth } from '../../auth/use-auth';
const publicLinks = [['/tramites','Tramites'], ['/noticias','Noticias'], ['/avisos','Avisos'], ['/calendario','Calendario'], ['/oirs','OIRS']];
const portalLinks = [['/portal','Inicio'], ['/portal/requests','Solicitudes'], ['/portal/oirs','OIRS'], ['/portal/notifications','Notificaciones'], ['/portal/profile','Perfil']];
const intranetLinks = [['/intranet','Inicio'], ['/intranet/documents','Documentos'], ['/intranet/expedients','Expedientes'], ['/intranet/correspondence','Correspondencia'], ['/intranet/oirs','OIRS'], ['/intranet/reports','Reportes'], ['/intranet/notifications','Notificaciones']];
function Shell({ title, links, admin = false }: { title: string; links: string[][]; admin?: boolean }) { const { session, signOut } = useAuth(); return <div className={admin ? 'shell admin' : 'shell'}><aside><Link to="/">SIGED Lampa</Link><nav>{links.map(([to, label]) => <NavLink key={to} to={to}>{label}</NavLink>)}</nav></aside><main><header className="topbar"><span>{title}</span><span data-testid="authenticated-user" data-actor={session?.actorType}>{session?.user.full_name || session?.user.email || session?.user.username}</span><button onClick={() => void signOut()}>Cerrar sesion</button></header><Outlet /></main></div>; }
export function PublicLayout() { return <div className="public"><header><Link to="/">SIGED Lampa</Link><nav>{publicLinks.map(([to,label]) => <NavLink key={to} to={to}>{label}</NavLink>)}<NavLink to="/login">Ingresar</NavLink></nav></header><main><Outlet /></main><footer>Municipalidad de Lampa</footer></div>; }
export const CitizenPortalLayout = () => <Shell title="Portal ciudadano" links={portalLinks} />;
export const IntranetLayout = () => <Shell title="Intranet" links={intranetLinks} />;
export const AdminLayout = () => <Shell title="Administracion" admin links={[...intranetLinks, ['/intranet/admin/users','Usuarios'], ['/intranet/admin/departments','Departamentos'], ['/intranet/admin/procedure-types','Tipos de tramites'], ['/intranet/admin/external-entities','Entidades externas'], ['/intranet/admin/public-content','Contenido publico']]} />;
