import { useEffect, useRef, useState, type RefObject } from 'react'
import { useForm, type UseFormReturn } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { oirsApi, type OirsCase, type OirsCreation, type OirsMessage } from '../../api/oirs.api'
import { DetailSection, PageHeader } from '../../components/domain'
import { EmptyState, ErrorState } from '../../components/feedback'
import { FormField, SelectField } from '../../components/forms'
import { SectionCard } from '../../components/ui'
import { StatusBadge } from '../../components/tables'
import { formatDateTime } from '../../utils/presentation'

const oirsSchema = z.object({ category: z.string().min(1, 'Seleccione un tipo'), subject: z.string().min(3, 'Indique un asunto').max(300), body: z.string().min(20, 'Describa su solicitud con al menos 20 caracteres').max(5000), name: z.string().min(1, 'Indique su nombre'), email: z.string().email('Indique un correo válido'), consent: z.boolean().refine(Boolean, 'Debe aceptar el consentimiento') })
type OirsForm = z.infer<typeof oirsSchema>
const categoryLabel = (value: string) => ({ consulta: 'Consulta', reclamo: 'Reclamo', sugerencia: 'Sugerencia', felicitacion: 'Felicitación', solicitud: 'Solicitud' }[value] || value.replace(/_/g, ' '))
const blocked = (status?: string) => status === 'closed' || status === 'cancelled'

function TrackingCredential({ label, value, testId, onCopy }: { label: string; value: string; testId?: string; onCopy: (value: string) => void }) {
  return <div className="tracking-credential"><span className="tracking-credential-label">{label}</span><code data-testid={testId}>{value}</code><button type="button" onClick={() => onCopy(value)}><i className="bi bi-copy" aria-hidden="true" />Copiar código</button></div>
}

export function PublicOirsPage() {
  const [mode, setMode] = useState<'create' | 'track'>('create'); const [created, setCreated] = useState<OirsCreation>(); const [tracked, setTracked] = useState<OirsCase>(); const [messages, setMessages] = useState<OirsMessage[]>([]); const [caseId, setCaseId] = useState(''); const [tracking, setTracking] = useState(''); const [message, setMessage] = useState(''); const [createError, setCreateError] = useState<Error>(); const [trackingError, setTrackingError] = useState<Error>(); const [messageError, setMessageError] = useState<Error>(); const [trackingLoading, setTrackingLoading] = useState(false); const [sendingMessage, setSendingMessage] = useState(false); const [copyNotice, setCopyNotice] = useState(''); const [messageNotice, setMessageNotice] = useState(''); const successRef = useRef<HTMLElement>(null); const resultRef = useRef<HTMLElement>(null);
  const form = useForm<OirsForm>({ resolver: zodResolver(oirsSchema), defaultValues: { category: '', subject: '', body: '', name: '', email: '', consent: false } }); const description = form.watch('body') || '';
  useEffect(() => { if (created) successRef.current?.focus(); }, [created]); useEffect(() => { if (tracked) resultRef.current?.focus(); }, [tracked]);
  const copy = async (value: string) => { try { if (!navigator.clipboard?.writeText) throw new Error(); await navigator.clipboard.writeText(value); setCopyNotice('Código copiado'); } catch { setCopyNotice('No fue posible copiar el código. Selecciónalo y cópialo manualmente.'); } };
  const submit = form.handleSubmit(async (data) => { setCreateError(undefined); try { const result = await oirsApi.create(data); setCreated(result.data); setCaseId(result.data.uuid); setTracking(result.data.tracking_token); form.reset(); } catch (cause) { setCreateError(cause as Error); } });
  const track = async (token = tracking, id = tracked?.uuid || caseId || created?.uuid) => { if (!token) { setTrackingError(new Error('Ingrese el código de seguimiento')); return; } if (!id) { setTrackingError(new Error('Ingrese el identificador público del caso')); return; } setTrackingLoading(true); setTrackingError(undefined); try { const [detail, history] = await Promise.all([oirsApi.detail(id, token), oirsApi.history(id, token)]); setTracked(detail.data); setMessages(history.data); setCaseId(id); setTracking(token); } catch (cause) { setTracked(undefined); setMessages([]); setTrackingError(cause as Error); } finally { setTrackingLoading(false); } };
  const postMessage = async () => { const activeCaseId = tracked?.uuid || caseId || created?.uuid; const activeTrackingToken = tracking || created?.tracking_token; if (!activeCaseId || !activeTrackingToken) { setMessageError(new Error('Ingrese el identificador y código de seguimiento del caso')); return; } if (blocked(tracked?.status)) { setMessageError(new Error('Este caso ya no admite nuevos mensajes.')); return; } if (!message.trim()) { setMessageError(new Error('Ingrese un mensaje')); return; } setSendingMessage(true); setMessageError(undefined); setMessageNotice(''); try { const result = await oirsApi.postMessage(activeCaseId, activeTrackingToken, message.trim()); setMessages((items) => [...items, result.data]); setMessage(''); setMessageNotice('Mensaje enviado correctamente.'); } catch (cause) { setMessageError(cause as Error); } finally { setSendingMessage(false); } };
  return <div className="oirs-page"><PageHeader title="Oficina de Informaciones, Reclamos y Sugerencias" description="Puede ingresar una nueva solicitud o consultar un caso existente." /><div className="oirs-tabs" role="tablist" aria-label="Opciones OIRS"><button role="tab" id="oirs-create-tab" aria-selected={mode === 'create'} aria-controls="oirs-create-panel" className={mode === 'create' ? 'active' : ''} onClick={() => setMode('create')}><i className="bi bi-pencil-square" aria-hidden="true" />Ingresar una solicitud</button><button role="tab" id="oirs-track-tab" aria-selected={mode === 'track'} aria-controls="oirs-track-panel" className={mode === 'track' ? 'active' : ''} onClick={() => setMode('track')}><i className="bi bi-search" aria-hidden="true" />Consultar seguimiento</button></div>{mode === 'create' && (created ? <SuccessCard focusRef={successRef} created={created} copy={copy} copyNotice={copyNotice} onTrack={() => { setMode('track'); void track(created.tracking_token, created.uuid); }} onNew={() => { setCreated(undefined); setTracked(undefined); setMessages([]); setCopyNotice(''); }} /> : <CreateForm form={form} description={description} submit={submit} error={createError} />)}{mode === 'track' && <section id="oirs-track-panel" role="tabpanel" aria-labelledby="oirs-track-tab" className="section-stack"><TrackingForm caseId={caseId} tracking={tracking} onCaseId={setCaseId} onTracking={setTracking} onTrack={() => void track()} loading={trackingLoading} error={trackingError} />{tracked && <CaseDetails focusRef={resultRef} item={tracked} messages={messages} message={message} onMessage={setMessage} onSend={() => void postMessage()} sending={sendingMessage} error={messageError} notice={messageNotice} />}</section>}</div>
}

function CreateForm({ form, description, submit, error }: { form: UseFormReturn<OirsForm>; description: string; submit: () => void; error?: Error }) { return <form id="oirs-create-panel" role="tabpanel" aria-labelledby="oirs-create-tab" onSubmit={submit} className="section-stack"><SectionCard><h2>Tipo de solicitud</h2><SelectField label="Tipo de caso" {...form.register('category')} error={form.formState.errors.category?.message}><option value="">Seleccione</option><option value="consulta">Consulta</option><option value="reclamo">Reclamo</option><option value="sugerencia">Sugerencia</option><option value="felicitacion">Felicitación</option><option value="solicitud">Solicitud</option></SelectField></SectionCard><SectionCard><h2>Antecedentes</h2><FormField label="Asunto" {...form.register('subject')} error={form.formState.errors.subject?.message} /><label className="field" htmlFor="oirs-description">Descripción<textarea id="oirs-description" aria-label="Descripción" {...form.register('body')} aria-invalid={Boolean(form.formState.errors.body)} aria-describedby="oirs-description-help" maxLength={5000} /><small id="oirs-description-help">{description.length}/5000 caracteres</small>{form.formState.errors.body && <span role="alert">{form.formState.errors.body.message}</span>}</label></SectionCard><SectionCard><h2>Datos de contacto</h2><div className="form-grid"><FormField label="Nombre" {...form.register('name')} error={form.formState.errors.name?.message} /><FormField label="Correo electrónico" type="email" {...form.register('email')} error={form.formState.errors.email?.message} /></div></SectionCard><SectionCard><h2>Consentimiento</h2><label className="oirs-consent"><input type="checkbox" {...form.register('consent')} />Acepto el tratamiento de mis datos para gestionar y responder esta solicitud OIRS</label>{form.formState.errors.consent && <span role="alert">{form.formState.errors.consent.message}</span>}</SectionCard>{error && <ErrorState error={error} />}<button className="button" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? 'Enviando solicitud...' : 'Enviar solicitud'}</button></form> }

const SuccessCard = ({ created, copy, copyNotice, onTrack, onNew, focusRef }: { created: OirsCreation; copy: (value: string) => void; copyNotice: string; onTrack: () => void; onNew: () => void; focusRef: RefObject<HTMLElement | null> }) => <section ref={focusRef} className="card oirs-success" tabIndex={-1}><i className="bi bi-check-circle-fill" aria-hidden="true" /><div><h2>Solicitud OIRS registrada</h2><p>Tu solicitud fue registrada correctamente. Guarda estos datos para consultar su estado y enviar nuevos antecedentes.</p></div><div className="tracking-credentials"><TrackingCredential label="Identificador del caso" value={created.uuid} onCopy={copy} />{created.tracking_code && <TrackingCredential label="Código público de seguimiento" value={created.tracking_code} onCopy={copy} />}<TrackingCredential label="Token de seguimiento" value={created.tracking_token} testId="oirs-tracking-token" onCopy={copy} /></div><p className="oirs-privacy"><i className="bi bi-shield-lock" aria-hidden="true" />El código de seguimiento permite acceder a la información del caso. No lo compartas públicamente.</p><p role="status" aria-live="polite">{copyNotice}</p><div className="page-actions"><button className="button" onClick={onTrack}>Consultar seguimiento</button><button type="button" onClick={onNew}>Registrar nueva solicitud</button></div></section>

function TrackingForm({ caseId, tracking, onCaseId, onTracking, onTrack, loading, error }: { caseId: string; tracking: string; onCaseId: (value: string) => void; onTracking: (value: string) => void; onTrack: () => void; loading: boolean; error?: Error }) { return <SectionCard><h2>Consultar seguimiento</h2><p className="section-copy">Ingrese los datos entregados al registrar su solicitud.</p><FormField label="Identificador del caso" value={caseId} onChange={(event) => onCaseId(event.target.value)} aria-describedby="oirs-case-id-help" /><small id="oirs-case-id-help">Ingresa el identificador que recibiste al registrar la solicitud.</small><label className="field" htmlFor="oirs-tracking-token-input">Código de seguimiento<textarea id="oirs-tracking-token-input" className="tracking-input" value={tracking} onChange={(event) => onTracking(event.target.value)} aria-describedby="oirs-tracking-help" rows={3} /></label><small id="oirs-tracking-help">Pega el código de seguimiento completo. Este dato se utiliza como credencial de acceso al caso.</small>{error && <ErrorState error={error} />}<button type="button" className="button" onClick={onTrack} disabled={loading}>{loading ? 'Consultando estado...' : <><i className="bi bi-search" aria-hidden="true" />Consultar estado</>}</button></SectionCard> }

const CaseDetails = ({ item, messages, message, onMessage, onSend, sending, error, notice, focusRef }: { item: OirsCase; messages: OirsMessage[]; message: string; onMessage: (value: string) => void; onSend: () => void; sending: boolean; error?: Error; notice: string; focusRef: RefObject<HTMLElement | null> }) => <section className="section-stack" ref={focusRef} tabIndex={-1}><SectionCard className="oirs-case-summary"><div className="page-actions"><div><p className="eyebrow">Caso OIRS</p><h2>{item.subject}</h2></div><span data-testid="oirs-status"><StatusBadge value={item.status} /></span></div><DetailSection title="Datos del caso"><dl className="metadata-grid"><div><dt>Categoría</dt><dd>{categoryLabel(item.category)}</dd></div><div><dt>Ingresado</dt><dd>{formatDateTime(item.submitted_at)}</dd></div><div><dt>Identificador</dt><dd className="long-value">{item.uuid}</dd></div>{item.tracking_code && <div><dt>Código público</dt><dd className="long-value">{item.tracking_code}</dd></div>}</dl></DetailSection></SectionCard><DetailSection title="Historial de mensajes">{messages.length ? <ol className="oirs-message-timeline" data-testid="oirs-messages">{messages.map((entry) => { const citizen = entry.message_direction !== 'from_officer'; return <li className={citizen ? 'from-citizen' : 'from-officer'} key={entry.id}><strong><i className={`bi ${citizen ? 'bi-person' : 'bi-building'}`} aria-hidden="true" />{citizen ? 'Ciudadano' : 'Municipalidad de Lampa'}</strong><time dateTime={entry.sent_at}>{formatDateTime(entry.sent_at)}</time><p className="oirs-message-body">{entry.body}</p></li> })}</ol> : <EmptyState title="Aún no hay mensajes" message="Las comunicaciones relacionadas con el caso aparecerán en esta sección." />}</DetailSection><DetailSection title="Nuevo mensaje"><p className="section-copy">Agregue antecedentes adicionales para este caso.</p><label className="field" htmlFor="oirs-new-message">Nuevo mensaje<textarea id="oirs-new-message" aria-label="Nuevo mensaje" value={message} onChange={(event) => onMessage(event.target.value)} disabled={blocked(item.status) || sending} maxLength={5000} /><small>{message.length}/5000 caracteres</small></label>{blocked(item.status) && <p className="oirs-closed-notice" role="status">Este caso ya no admite nuevos mensajes.</p>}{error && <ErrorState error={error} />}<p role="status" aria-live="polite">{notice}</p><button type="button" className="button" onClick={onSend} disabled={blocked(item.status) || sending}>{sending ? 'Enviando mensaje...' : 'Enviar mensaje'}</button></DetailSection></section>
