const { query } = require('../../database/pool');

const paging = (values) => [values.size, (values.page - 1) * values.size];
const publicNews = (values) => query('SELECT id,uuid,slug,title,summary,published_at FROM news_posts WHERE status=\'published\' AND published_at <= now() AND deleted_at IS NULL ORDER BY published_at DESC LIMIT $1 OFFSET $2', paging(values));
const publicNewsBySlug = (slug) => query('SELECT id,uuid,slug,title,summary,content_html,published_at FROM news_posts WHERE slug=$1 AND status=\'published\' AND published_at <= now() AND deleted_at IS NULL', [slug]);
const publicNotices = (values) => query('SELECT id,uuid,title,body_html,notice_type,start_at,end_at FROM public_notices WHERE status=\'active\' AND start_at <= now() AND end_at >= now() ORDER BY start_at DESC LIMIT $1 OFFSET $2', paging(values));
const publicCalendar = (values) => query('SELECT id,uuid,title,description,start_at,end_at,location,status FROM calendar_events WHERE audience=\'public\' AND status IN (\'scheduled\',\'confirmed\') AND end_at >= now() ORDER BY start_at LIMIT $1 OFFSET $2', paging(values));
const adminList = (table) => query(`SELECT * FROM ${table} ORDER BY created_at DESC`);
const createNews = (db, value, actorId) => db.query('INSERT INTO news_posts (slug,title,summary,content_html,status,author_user_id,published_at) VALUES ($1,$2,$3,$4,$5::varchar,$6,CASE WHEN $5=\'published\' THEN now() ELSE NULL END) RETURNING *', [value.slug, value.title, value.summary || null, value.content_html, value.status, actorId]);
const updateNews = (db, id, value) => db.query('UPDATE news_posts SET slug=$2,title=$3,summary=$4,content_html=$5,status=$6::varchar,published_at=CASE WHEN $6=\'published\' AND published_at IS NULL THEN now() WHEN $6<>\'published\' THEN NULL ELSE published_at END,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING *', [id, value.slug, value.title, value.summary || null, value.content_html, value.status]);
const createNotice = (db, value, actorId) => db.query('INSERT INTO public_notices (title,body_html,notice_type,status,start_at,end_at,author_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [value.title, value.body_html, value.notice_type, value.status, value.start_at, value.end_at, actorId]);
const updateNotice = (db, id, value) => db.query('UPDATE public_notices SET title=$2,body_html=$3,notice_type=$4,status=$5,start_at=$6,end_at=$7,updated_at=now() WHERE id=$1 RETURNING *', [id, value.title, value.body_html, value.notice_type, value.status, value.start_at, value.end_at]);
const createCalendar = (db, value, actorId) => db.query('INSERT INTO calendar_events (title,description,start_at,end_at,audience,location,status,department_id,owner_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *', [value.title, value.description || null, value.start_at, value.end_at, value.audience, value.location || null, value.status, value.department_id || null, actorId]);
const updateCalendar = (db, id, value) => db.query('UPDATE calendar_events SET title=$2,description=$3,start_at=$4,end_at=$5,audience=$6,location=$7,status=$8,department_id=$9,updated_at=now() WHERE id=$1 RETURNING *', [id, value.title, value.description || null, value.start_at, value.end_at, value.audience, value.location || null, value.status, value.department_id || null]);

module.exports = { publicNews, publicNewsBySlug, publicNotices, publicCalendar, adminList, createNews, updateNews, createNotice, updateNotice, createCalendar, updateCalendar };
