from __future__ import annotations

from pathlib import Path
from typing import Any
from datetime import datetime, timezone
import json

ARCHITECTURE_SCHEMA = "webforge.architecture.v1"

FACTORY_COMPONENTS: list[dict[str, Any]] = [
    {
        "component_id": "comp.cli",
        "name": "CLI",
        "type": "factory",
        "responsibility": "Entry point for agent orchestration via command line",
        "inputs": ["user_commands"],
        "outputs": ["work_orders"],
        "dependencies": [],
        "owned_by_agent": "agent.entrypoint",
        "related_modules": ["webforge.cli"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.work_order_loader",
        "name": "WorkOrderLoader",
        "type": "factory",
        "responsibility": "Loads and deserializes work orders from intake sources",
        "inputs": ["work_orders"],
        "outputs": ["parsed_work_orders"],
        "dependencies": [],
        "owned_by_agent": "agent.intake",
        "related_modules": ["webforge.intake"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.normalizer",
        "name": "Normalizer",
        "type": "factory",
        "responsibility": "Parses and normalises raw specification documents into a structured spec tree",
        "inputs": ["parsed_work_orders", "raw_specs"],
        "outputs": ["normalised_specs"],
        "dependencies": [],
        "owned_by_agent": "agent.spec_parser",
        "related_modules": ["webforge.spec_parser"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.planner",
        "name": "Planner",
        "type": "factory",
        "responsibility": "Generates architecture plans and decomposes work into tasks",
        "inputs": ["normalised_specs"],
        "outputs": ["architecture_plan", "task_list"],
        "dependencies": ["comp.normalizer"],
        "owned_by_agent": "agent.architect_planner",
        "related_modules": ["webforge.architect_planner"],
        "related_codes": [],
        "implementation_status": "planned",
    },
    {
        "component_id": "comp.dag_scheduler",
        "name": "DAGScheduler",
        "type": "factory",
        "responsibility": "Arranges tasks into a DAG respecting dependencies and critical path",
        "inputs": ["task_list"],
        "outputs": ["dag"],
        "dependencies": ["comp.planner"],
        "owned_by_agent": "agent.task_planner",
        "related_modules": ["webforge.task_planner"],
        "related_codes": [],
        "implementation_status": "planned",
    },
    {
        "component_id": "comp.harness_runner",
        "name": "HarnessRunner",
        "type": "factory",
        "responsibility": "Executes tasks in the DAG and verifies consistency of outputs",
        "inputs": ["dag", "task_artifacts"],
        "outputs": ["validated_artifacts", "review_reports"],
        "dependencies": ["comp.dag_scheduler"],
        "owned_by_agent": "agent.consistency_reviewer",
        "related_modules": ["webforge.consistency_reviewer"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.policy_engine",
        "name": "PolicyEngine",
        "type": "factory",
        "responsibility": "Enforces governance policies and rules across the pipeline",
        "inputs": ["policy_definitions"],
        "outputs": ["policy_decisions"],
        "dependencies": [],
        "owned_by_agent": "governance",
        "related_modules": ["webforge.governance"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.budget_manager",
        "name": "BudgetManager",
        "type": "factory",
        "responsibility": "Tracks token and resource budgets for agentic runs",
        "inputs": ["budget_config"],
        "outputs": ["budget_reports"],
        "dependencies": [],
        "owned_by_agent": "governance",
        "related_modules": ["webforge.governance"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.tool_registry",
        "name": "ToolRegistry",
        "type": "factory",
        "responsibility": "Registry of available tools that agents can invoke",
        "inputs": ["tool_definitions"],
        "outputs": ["tool_catalog"],
        "dependencies": [],
        "owned_by_agent": "tool_registry",
        "related_modules": ["webforge.tool_registry"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.evidence_registry",
        "name": "EvidenceRegistry",
        "type": "factory",
        "responsibility": "Stores and indexes evidence produced during pipeline execution",
        "inputs": ["evidence_artifacts"],
        "outputs": ["evidence_index"],
        "dependencies": [],
        "owned_by_agent": "evidence",
        "related_modules": ["webforge.evidence"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.workspace_dev",
        "name": "WorkspaceDEV",
        "type": "factory",
        "responsibility": "Isolated development workspace for code generation and testing",
        "inputs": ["task_artifacts"],
        "outputs": ["generated_code", "test_reports"],
        "dependencies": [],
        "owned_by_agent": "workspace",
        "related_modules": ["webforge.workspace"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.workspace_qa",
        "name": "WorkspaceQA",
        "type": "factory",
        "responsibility": "Isolated QA workspace for validation and review",
        "inputs": ["generated_code", "test_reports"],
        "outputs": ["qa_reports"],
        "dependencies": ["comp.workspace_dev"],
        "owned_by_agent": "workspace",
        "related_modules": ["webforge.workspace"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.agent_qa_release",
        "name": "AgentQARelease",
        "type": "factory",
        "responsibility": "Coordinates QA signoff and release approval gate",
        "inputs": ["qa_reports"],
        "outputs": ["release_approval"],
        "dependencies": ["comp.workspace_qa"],
        "owned_by_agent": "qa_release",
        "related_modules": ["webforge.qa_release"],
        "related_codes": [],
        "implementation_status": "planned",
    },
]

PRODUCT_COMPONENTS: list[dict[str, Any]] = [
    {
        "component_id": "comp.frontend_web",
        "name": "FrontendWeb",
        "type": "product",
        "responsibility": "Vanilla JS single-page application serving the municipal interface",
        "inputs": ["api_responses"],
        "outputs": ["http_requests", "ui_events"],
        "dependencies": ["comp.backend_api"],
        "owned_by_agent": "frontend",
        "related_modules": ["frontend"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.backend_api",
        "name": "BackendAPI",
        "type": "product",
        "responsibility": "Node HTTP API gateway that routes requests to domain services",
        "inputs": ["http_requests"],
        "outputs": ["api_responses", "service_calls"],
        "dependencies": ["comp.servicio_autenticacion_academica", "comp.servicio_documental", "comp.servicio_expedientes", "comp.repositorio_postgresql"],
        "owned_by_agent": "backend",
        "related_modules": ["backend"],
        "related_codes": [],
        "implementation_status": "existing",
    },
    {
        "component_id": "comp.servicio_autenticacion_academica",
        "name": "ServicioAutenticacionAcademica",
        "type": "product",
        "responsibility": "Academic authentication and identity management service",
        "inputs": ["auth_requests"],
        "outputs": ["auth_tokens", "identity_data"],
        "dependencies": ["comp.repositorio_postgresql"],
        "owned_by_agent": "auth",
        "related_modules": ["backend.services.autenticacion"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.servicio_documental",
        "name": "ServicioDocumental",
        "type": "product",
        "responsibility": "Document management and archival service",
        "inputs": ["document_requests"],
        "outputs": ["document_data", "file_references"],
        "dependencies": ["comp.repositorio_postgresql", "comp.almacenamiento_archivos_simulado"],
        "owned_by_agent": "document",
        "related_modules": ["backend.services.documental"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.servicio_expedientes",
        "name": "ServicioExpedientes",
        "type": "product",
        "responsibility": "Expedient (case file) tracking and management service",
        "inputs": ["expedient_requests"],
        "outputs": ["expedient_data"],
        "dependencies": ["comp.repositorio_postgresql"],
        "owned_by_agent": "expedient",
        "related_modules": ["backend.services.expedientes"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.servicio_correspondencia",
        "name": "ServicioCorrespondencia",
        "type": "product",
        "responsibility": "Internal and external correspondence tracking service",
        "inputs": ["correspondence_requests"],
        "outputs": ["correspondence_data"],
        "dependencies": ["comp.repositorio_postgresql", "comp.servicio_documental"],
        "owned_by_agent": "correspondence",
        "related_modules": ["backend.services.correspondencia"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.servicio_ciudadano",
        "name": "ServicioCiudadano",
        "type": "product",
        "responsibility": "Citizen profile and relationship management service",
        "inputs": ["citizen_requests"],
        "outputs": ["citizen_data"],
        "dependencies": ["comp.repositorio_postgresql"],
        "owned_by_agent": "citizen",
        "related_modules": ["backend.services.ciudadano"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.servicio_oirs",
        "name": "ServicioOIRS",
        "type": "product",
        "responsibility": "OIRS (citizen complaints and requests) service",
        "inputs": ["oirs_requests"],
        "outputs": ["oirs_data", "notifications"],
        "dependencies": ["comp.repositorio_postgresql", "comp.servicio_notificaciones"],
        "owned_by_agent": "oirs",
        "related_modules": ["backend.services.oirs"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.servicio_notificaciones",
        "name": "ServicioNotificaciones",
        "type": "product",
        "responsibility": "Notification dispatch service (email, SMS, in-app)",
        "inputs": ["notification_requests"],
        "outputs": ["notifications_sent"],
        "dependencies": [],
        "owned_by_agent": "notification",
        "related_modules": ["backend.services.notificaciones"],
        "related_codes": [],
        "implementation_status": "planned",
    },
    {
        "component_id": "comp.servicio_reportabilidad",
        "name": "ServicioReportabilidad",
        "type": "product",
        "responsibility": "Reporting and analytics service for generating structured reports",
        "inputs": ["report_requests"],
        "outputs": ["reports"],
        "dependencies": ["comp.repositorio_postgresql"],
        "owned_by_agent": "reporting",
        "related_modules": ["backend.services.reportabilidad"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.repositorio_postgresql",
        "name": "RepositorioPostgreSQL",
        "type": "product",
        "responsibility": "Central PostgreSQL database repository for all domain data",
        "inputs": ["queries", "mutations"],
        "outputs": ["result_sets", "acknowledgements"],
        "dependencies": [],
        "owned_by_agent": "database",
        "related_modules": ["backend.database"],
        "related_codes": [],
        "implementation_status": "planned",
    },
    {
        "component_id": "comp.almacenamiento_archivos_simulado",
        "name": "AlmacenamientoArchivosSimulado",
        "type": "product",
        "responsibility": "Simulated file storage service for development and testing",
        "inputs": ["file_operations"],
        "outputs": ["file_handles", "storage_events"],
        "dependencies": [],
        "owned_by_agent": "storage",
        "related_modules": ["backend.storage"],
        "related_codes": [],
        "implementation_status": "partial",
    },
    {
        "component_id": "comp.auditoria",
        "name": "Auditoria",
        "type": "product",
        "responsibility": "Audit logging and traceability service for all domain operations",
        "inputs": ["audit_events"],
        "outputs": ["audit_trail"],
        "dependencies": ["comp.repositorio_postgresql"],
        "owned_by_agent": "audit",
        "related_modules": ["backend.services.auditoria"],
        "related_codes": [],
        "implementation_status": "partial",
    },
]


def build_architecture(
    project_id: str,
    project_version: str,
    source_hashes: dict[str, str],
    decisions: list[dict[str, Any]],
    agents: list[dict[str, Any]],
    components: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build the full architecture document for the SIGED-Lampa project."""
    components_list = components if components is not None else FACTORY_COMPONENTS + PRODUCT_COMPONENTS

    return {
        "schema_version": ARCHITECTURE_SCHEMA,
        "project_id": project_id,
        "project_version": project_version,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_hashes": source_hashes,
        "product": {
            "status": "partial",
            "coverage": 0,
            "endpoints_implemented": 8,
            "endpoints_documented": 40,
            "screens_implemented": 3,
            "screens_documented": 30,
            "tables_implemented": 6,
            "tables_documented": 40,
        },
        "factory": {
            "status": "complete",
            "components": 13,
            "agents": 6,
        },
        "components": components_list,
        "data_flows": [
            {"from": "FrontendWeb", "to": "BackendAPI", "protocol": "HTTP", "auth": "simulated_jwt"},
            {
                "from": "BackendAPI",
                "to": "RepositorioPostgreSQL",
                "protocol": "postgresql",
                "auth": "password",
                "status": "planned",
            },
        ],
        "deployment_units": [
            {"name": "frontend", "type": "static", "target": "node_http", "status": "existing"},
            {"name": "backend", "type": "node", "target": "node_http", "status": "existing"},
            {"name": "database", "type": "postgresql", "target": "rds_ec2", "status": "planned"},
        ],
        "security_boundaries": [
            {
                "name": "intranet",
                "type": "authenticated",
                "actors": ["ACT-ADM", "ACT-FUN", "ACT-OPA", "ACT-REV", "ACT-OIR", "ACT-REP"],
            },
            {
                "name": "portal",
                "type": "public_or_authenticated",
                "actors": ["ACT-CIU", "ACT-VIS"],
            },
            {
                "name": "admin",
                "type": "admin_only",
                "actors": ["ACT-ADM"],
            },
            {
                "name": "external",
                "type": "unauthenticated_limited",
                "actors": ["ACT-EXT"],
            },
        ],
        "quality_gates": [
            {"name": "GATE-ARCH-001", "description": "Sources normalized with 0 blocking", "phase": "planning"},
            {"name": "GATE-ARCH-002", "description": "Critical decisions accepted", "phase": "planning"},
            {"name": "GATE-ARCH-003", "description": "Agents valid", "phase": "planning"},
            {"name": "GATE-ARCH-004", "description": "Tasks valid", "phase": "planning"},
            {"name": "GATE-ARCH-005", "description": "DAG acyclic", "phase": "planning"},
            {"name": "GATE-ARCH-006", "description": "Handoffs valid", "phase": "planning"},
            {"name": "GATE-ARCH-007", "description": "Baseline preserved", "phase": "planning"},
        ],
        "decisions": decisions,
        "status": "planned",
    }


def write_architecture(output_dir: Path, architecture: dict[str, Any]) -> Path:
    """Write the architecture document as architecture.json to output_dir."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "architecture.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(architecture, f, indent=2, ensure_ascii=False)
    return output_path


def load_catalogs(spec_dir: Path) -> dict[str, Any]:
    """Read all JSON files from spec_dir and return {filename_stem: data}."""
    catalogs: dict[str, Any] = {}
    for path in sorted(spec_dir.glob("*.json")):
        with open(path, "r", encoding="utf-8") as f:
            catalogs[path.stem] = json.load(f)
    return catalogs
