const express = require('express');
const authenticate = require('../../middleware/authentication');
const authorize = require('../../middleware/authorization');
const controller = require('./controller');
const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res)).catch(next);
const router = express.Router();
router.get('/api/v1/documents', authenticate, authorize('documents.view'), wrap(controller.list));
router.post('/api/v1/documents', authenticate, authorize('documents.create'), wrap(controller.create));
router.get('/api/v1/documents/:id', authenticate, authorize('documents.view'), wrap(controller.detail));
router.put('/api/v1/documents/:id', authenticate, authorize('documents.edit'), wrap(controller.update));
router.get('/api/v1/documents/:id/versions', authenticate, authorize('documents.view'), wrap(controller.versions));
router.post('/api/v1/documents/:id/versions', authenticate, authorize('documents.edit'), wrap(controller.createVersion));
router.get('/api/v1/documents/:id/attachments', authenticate, authorize('documents.view'), wrap(controller.attachments));
router.post('/api/v1/documents/:id/attachments', authenticate, authorize('documents.edit'), wrap(controller.addAttachment));
router.get('/api/v1/documents/:id/attachments/:attachmentId/download', authenticate, authorize('documents.view'), wrap(controller.download));
router.get('/api/v1/documents/:id/comments', authenticate, authorize('documents.view'), wrap(controller.comments));
router.post('/api/v1/documents/:id/comments', authenticate, authorize('documents.review'), wrap(controller.addComment));
router.get('/api/v1/documents/:id/history', authenticate, authorize('documents.view'), wrap(controller.history));
module.exports = router;
