const { transaction } = require('../../database/transaction');
const { query } = require('../../database/pool');
const { AppError } = require('../../shared/errors');
const audit = require('../../shared/audit');
const storage = require('../storage/service');
const repository = require('./repository');

function ensureReadable(document, actor) { if (!document) throw new AppError(404, 'DOCUMENT_NOT_FOUND', 'Documento no encontrado'); if (document.confidentiality_level === 'secret' && document.owner_user_id !== actor.id) throw new AppError(403, 'FORBIDDEN', 'No autorizado para este documento'); }
async function documentForRead(id, actor) { const document = await repository.findDocument({ query }, id); ensureReadable(document, actor); return document; }
async function list(filters, actor) { const result = await repository.list({ query }, filters, actor); return { items: result.rows, page: filters.page, size: filters.size, total: result.total }; }
async function create(data, actor, context) { return transaction(async (client) => { if (!await repository.typeExists(client, data.document_type_id)) throw new AppError(400, 'DOCUMENT_TYPE_NOT_FOUND', 'Tipo documental inválido'); if (!await repository.departmentExists(client, data.department_id)) throw new AppError(400, 'DEPARTMENT_NOT_FOUND', 'Departamento inválido'); const document = await repository.createDocument(client, data, actor.id); const version = await repository.createVersion(client, document.id, null, 1, data, actor.id); await repository.setCurrentVersion(client, document.id, version.id); await audit.record(client, { eventName: 'document_created', moduleCode: 'documents', entityType: 'document', entityId: document.id, actor, ipAddress: context.ip, payload: { version_id: version.id } }); return { ...document, current_version_id: version.id, version }; }); }
async function detail(id, actor) { await documentForRead(id, actor); return repository.detail({ query }, id); }
async function update(id, data, actor, context) { return transaction(async (client) => { const document = await repository.findDocument(client, id, true); ensureReadable(document, actor); if (document.status !== 'draft') throw new AppError(409, 'DOCUMENT_NOT_EDITABLE', 'El documento no puede editarse en su estado actual'); if (data.department_id && !await repository.departmentExists(client, data.department_id)) throw new AppError(400, 'DEPARTMENT_NOT_FOUND', 'Departamento inválido'); const changed = {}; for (const [key, value] of Object.entries(data)) if (document[key] !== value) changed[key] = value; if (!Object.keys(changed).length) return document; const updated = await repository.updateDocument(client, id, changed); await audit.record(client, { eventName: 'document_updated', moduleCode: 'documents', entityType: 'document', entityId: id, actor, ipAddress: context.ip, payload: { changes: changed } }); return updated; }); }
async function createVersion(id, data, actor, context) { return transaction(async (client) => { const document = await repository.findDocument(client, id, true); ensureReadable(document, actor); if (document.status !== 'draft') throw new AppError(409, 'DOCUMENT_NOT_VERSIONABLE', 'El documento no admite nuevas versiones'); if (!document.current_version_id) throw new AppError(409, 'CURRENT_VERSION_REQUIRED', 'El documento no tiene una versión vigente'); const previous = await client.query('SELECT id,version_number FROM document_versions WHERE id=$1 AND document_id=$2 FOR UPDATE', [document.current_version_id, id]); if (!previous.rows[0]) throw new AppError(409, 'INVALID_CURRENT_VERSION', 'La versión vigente es inválida'); const version = await repository.createVersion(client, id, previous.rows[0].id, previous.rows[0].version_number + 1, data, actor.id); await repository.setCurrentVersion(client, id, version.id); await audit.record(client, { eventName: 'document_version_created', moduleCode: 'documents', entityType: 'document', entityId: id, actor, ipAddress: context.ip, payload: { version_id: version.id, version_number: version.version_number } }); return version; }); }
async function addAttachment(id, data, actor, context) { const prepared = storage.prepare(data); const stored = await storage.save(prepared); try { return await transaction(async (client) => { const document = await repository.findDocument(client, id, true); ensureReadable(document, actor); const versionId = data.document_version_id || document.current_version_id; const version = await client.query('SELECT id FROM document_versions WHERE id=$1 AND document_id=$2', [versionId, id]); if (!version.rows[0]) throw new AppError(400, 'DOCUMENT_VERSION_NOT_FOUND', 'La versión indicada no pertenece al documento'); const attachment = await repository.createAttachment(client, { documentId: id, versionId, fileName: prepared.fileName, mimeType: data.mime_type, storagePath: stored.storagePath, fileSize: stored.fileSize, checksum: stored.checksum, actorId: actor.id }); await audit.record(client, { eventName: 'document_attachment_added', moduleCode: 'documents', entityType: 'document', entityId: id, actor, ipAddress: context.ip, payload: { attachment_id: attachment.id, version_id: versionId, file_name: prepared.fileName, checksum_sha256: stored.checksum, description: data.description || null } }); return attachment; }); } catch (error) { await storage.remove(stored.storagePath); throw error; } }
async function attachment(id, attachmentId, actor) { await documentForRead(id, actor); const item = await repository.findAttachment({ query }, id, attachmentId); if (!item) throw new AppError(404, 'ATTACHMENT_NOT_FOUND', 'Anexo no encontrado'); return item; }
async function addComment(id, data, actor, context) { return transaction(async (client) => { const document = await repository.findDocument(client, id, true); ensureReadable(document, actor); if (data.version_id) { const version = await client.query('SELECT id FROM document_versions WHERE id=$1 AND document_id=$2', [data.version_id, id]); if (!version.rows[0]) throw new AppError(400, 'DOCUMENT_VERSION_NOT_FOUND', 'La versión indicada no pertenece al documento'); } const comment = await repository.createComment(client, { documentId: id, actorId: actor.id, ...data }); await audit.record(client, { eventName: 'document_comment_added', moduleCode: 'documents', entityType: 'document', entityId: id, actor, ipAddress: context.ip, payload: { comment_id: comment.id, comment_type: comment.comment_type, version_id: comment.version_id } }); return comment; }); }
module.exports = { list, create, detail, update, createVersion, addAttachment, attachment, addComment, versions: async (id, actor) => { await documentForRead(id, actor); return repository.listVersions({ query }, id); }, attachments: async (id, actor) => { await documentForRead(id, actor); return repository.listAttachments({ query }, id); }, comments: async (id, actor) => { await documentForRead(id, actor); return repository.listComments({ query }, id); }, history: async (id, actor) => { await documentForRead(id, actor); return repository.history({ query }, id); } };
