import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { api } from '../../api/endpoints'
import { citizenRequestsApi, type CitizenRequestDetail, type CitizenRequestList } from '../../api/citizen-requests.api'
import { getResource, mutateResource } from '../../api/resources'
import type { Procedure } from '../../api/types'
import { useAuth } from '../../auth/use-auth'
import { DetailSection, PageHeader } from '../../components/domain'
import { ConfirmDialog, EmptyState, ErrorState, LoadingState } from '../../components/feedback'
import { FormField } from '../../components/forms'
import { DataTable, DateCell, StatusBadge } from '../../components/tables'
import { formatDate, formatDateTime } from '../../utils/presentation'
import { PublicOirsPage } from '../oirs-public/PublicOirsPage'

const requestLoad = () => citizenRequestsApi.list({ page: 1, size: 100 })
export function CitizenDashboardPage() { const { session } = useAuth(); const [data, setData] = useState<CitizenRequestList>(); const [error, setError] = useState<Error>(); const load = () => { setError(undefined); requestLoad().then(({ data: value }) => setData(value)).catch((cause) => setError(cause as Error)) }; useEffect(load, []); const name = session?.user.full_name || session?.user.email || 'ciudadano'; if (error) return <><PageHeader title={`Hola, ${name}`} description="Consulta tus solicitudes, notificaciones y accesos disponibles." /><ErrorState error={error} onRetry={load} /></>; if (!data) return <><PageHeader title={`Hola, ${name}`} description="Consulta tus solicitudes, notificaciones y accesos disponibles." /><LoadingState /></>; const count = (status: string[]) => data.items.filter((item) => status.includes(item.status)).length; return <><PageHeader title={`Hola, ${name}`} description="Consulta tus solicitudes, notificaciones y accesos disponibles." />{!data.total ? <EmptyState title="Aún no tienes solicitudes" message="Puedes revisar los trámites disponibles e iniciar una nueva solicitud." action={<Link className="button" to="/portal/procedures">Buscar un trámite</Link>} /> : <><section className="metrics-grid"><article className="metric"><strong>{data.total}</strong><span>Total</span></article><article className="metric"><strong>{count(['submitted'])}</strong><span>Ingresadas</span></article><article className="metric"><strong>{count(['in_review', 'in_process'])}</strong><span>En revisión</span></article><article className="metric"><strong>{count(['completed', 'resolved'])}</strong><span>Resueltas</span></article><article className="metric"><strong>{count(['cancelled'])}</strong><span>Canceladas</span></article></section><DetailSection title="Solicitudes recientes"><DataTable columns={[{ key: 'tracking_code', label: 'Código', render: (value, row) => <Link to={`/portal/requests/${row.id}`}>{String(value)}</Link> }, { key: 'status', label: 'Estado', render: (value) => <StatusBadge value={String(value)} /> }, { key: 'submitted_at', label: 'Ingreso', render: (value) => <DateCell value={String(value)} /> }]} rows={data.items.slice(0, 5)} caption="Solicitudes recientes" /></DetailSection></>}<DetailSection title="Accesos rápidos"><div className="page-actions"><Link to="/portal/procedures">Buscar un trámite</Link><Link to="/portal/requests">Mis solicitudes</Link><Link to="/portal/oirs">Ingresar o consultar OIRS</Link><Link to="/portal/notifications">Notificaciones</Link><Link to="/portal/profile">Mi perfil</Link></div></DetailSection></> }

export function CitizenProceduresPage() { const [items, setItems] = useState<Procedure[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error>(); const [search, setSearch] = useState(''); const [department, setDepartment] = useState(''); const load = () => { setLoading(true); setError(undefined); api.procedures().then(({ data }) => setItems(data)).catch((cause) => setError(cause as Error)).finally(() => setLoading(false)) }; useEffect(load, []); const header = <PageHeader title="Trámites disponibles" description="Revise requisitos e inicie solicitudes sin salir de su portal." />; if (loading) return <>{header}<LoadingState /></>; if (error) return <>{header}<ErrorState error={error} onRetry={load} /></>; if (!items.length) return <>{header}<EmptyState title="No hay trámites disponibles" message="Actualmente no existen trámites publicados para iniciar en línea." /></>; const departments = [...new Set(items.map((item) => item.department_name).filter(Boolean))] as string[]; const filtered = items.filter((item) => `${item.title} ${item.instructions}`.toLowerCase().includes(search.toLowerCase()) && (!department || item.department_name === department)); return <>{header}<div className="filters"><input type="search" aria-label="Buscar trámites" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar trámites" /><select aria-label="Filtrar por departamento" value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">Todos los departamentos</option>{departments.map((name) => <option key={name}>{name}</option>)}</select></div>{!filtered.length ? <EmptyState title="No se encontraron trámites" message="Pruebe otra búsqueda o departamento." /> : <section className="public-card-grid">{filtered.map((item) => <article className="public-card" key={item.id}><p className="public-kicker">{item.department_name || 'Municipalidad de Lampa'}</p><h2>{item.title}</h2><p>{item.instructions}</p><div className="page-actions"><Link to={`/portal/procedures/${item.id}`}>Ver detalles</Link><Link className="button" to={`/portal/requests/new/${item.id}`}>Iniciar solicitud</Link></div></article>)}</section>}</> }

export function CitizenProcedureDetailPage() { const { procedureId = '' } = useParams(); const [item, setItem] = useState<Procedure>(); const [error, setError] = useState<Error>(); useEffect(() => { api.procedure(procedureId).then(({ data }) => setItem(data)).catch((cause) => setError(cause as Error)) }, [procedureId]); if (error) return <><PageHeader title="Trámite" /><ErrorState error={error} /></>; if (!item) return <LoadingState />; const safeRequirements = (item.requirements_html || 'No se informaron requisitos.').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim(); return <><PageHeader title={item.title} description={item.department_name} /><div className="page-actions"><Link to="/portal/procedures">Volver a trámites</Link><Link className="button" to={`/portal/requests/new/${item.id}`}>Iniciar solicitud</Link></div><DetailSection title="Instrucciones"><p>{item.instructions || 'No se informaron instrucciones.'}</p></DetailSection><DetailSection title="Requisitos"><p>{safeRequirements}</p></DetailSection></> }

export function CitizenRequestDetailPage() { const { requestId = '' } = useParams(); const [item, setItem] = useState<CitizenRequestDetail>(); const [error, setError] = useState<Error>(); const [confirm, setConfirm] = useState(false); const [cancelling, setCancelling] = useState(false); const [cancelError, setCancelError] = useState<Error>(); const [reason, setReason] = useState(''); const load = () => { setError(undefined); citizenRequestsApi.detail(requestId).then(({ data }) => setItem(data)).catch((cause) => setError(cause as Error)) }; useEffect(load, [requestId]); const cancel = async () => { setCancelling(true); setCancelError(undefined); try { await citizenRequestsApi.cancel(requestId, reason); await citizenRequestsApi.detail(requestId).then(({ data }) => setItem(data)); setConfirm(false) } catch (cause) { setCancelError(cause as Error) } finally { setCancelling(false) } }; if (error) return <><PageHeader title="Solicitud" /><ErrorState error={error} onRetry={load} /></>; if (!item) return <LoadingState />; const cancellable = ['submitted', 'in_review'].includes(item.status); return <><PageHeader title={item.procedure_title} description={`Código de seguimiento: ${item.tracking_code}`} /><div className="page-actions"><Link to="/portal/requests">Volver a mis solicitudes</Link>{cancellable && <button className="button-danger" onClick={() => setConfirm(true)}>Cancelar solicitud</button>}</div><DetailSection title="Estado de la solicitud"><StatusBadge value={item.status} /><dl className="metadata-grid"><div><dt>Ingresada</dt><dd>{formatDate(item.submitted_at)}</dd></div><div><dt>Resuelta</dt><dd>{formatDate(item.resolved_at)}</dd></div><div><dt>Identificador</dt><dd className="long-value">{item.uuid}</dd></div></dl>{item.resolution_summary && <p>{item.resolution_summary}</p>}</DetailSection><DetailSection title="Adjuntos">{item.attachments.length ? <ul className="file-list">{item.attachments.map((file) => <li key={file.id}>{file.file_name} <small>{file.mime_type} · {file.file_size} bytes</small></li>)}</ul> : <EmptyState title="Sin adjuntos" message="Esta solicitud no contiene archivos adjuntos." />}</DetailSection><DetailSection title="Historial">{item.history.length ? <ol className="timeline">{item.history.map((event, index) => <li key={`${event.event_name}-${index}`}><strong>{event.event_name.replace(/_/g, ' ')}</strong><small>{formatDateTime(event.occurred_at)}</small></li>)}</ol> : <EmptyState title="Sin historial" message="Aún no hay movimientos registrados." />}</DetailSection><ConfirmDialog open={confirm} title="¿Cancelar solicitud?" onClose={() => !cancelling && setConfirm(false)} onConfirm={() => void cancel()} confirmLabel="Cancelar solicitud" processing={cancelling} error={cancelError}><p>Esta acción marcará la solicitud como cancelada y no podrá deshacerse.</p><label className="field">Motivo opcional<textarea value={reason} onChange={(event) => setReason(event.target.value)} disabled={cancelling} /></label></ConfirmDialog></> }

const profileSchema = z.object({ full_name: z.string().min(3, 'Ingrese su nombre completo'), phone: z.string().trim().regex(/^$|^\+?[0-9() -]{7,40}$/, 'Ingrese un teléfono válido') }); type CitizenProfile = { id: number; email: string; full_name: string | null; phone: string | null; address: string | null; commune: string | null }
export function CitizenProfilePage() { const [profile, setProfile] = useState<CitizenProfile>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error>(); const [saved, setSaved] = useState(false); const form = useForm<z.infer<typeof profileSchema>>({ resolver: zodResolver(profileSchema), defaultValues: { full_name: '', phone: '' } }); const load = () => { setLoading(true); setError(undefined); getResource<CitizenProfile>('API-004').then(({ data }) => { setProfile(data); form.reset({ full_name: data.full_name || '', phone: data.phone || '' }) }).catch((cause) => setError(cause as Error)).finally(() => setLoading(false)) }; useEffect(load, []); const submit = form.handleSubmit(async (values) => { setSaved(false); setError(undefined); try { const response = await mutateResource<CitizenProfile>('API-005', { full_name: values.full_name, phone: values.phone || undefined }); setProfile(response.data); setSaved(true) } catch (cause) { setError(cause as Error) } }); if (loading) return <><PageHeader title="Mi perfil" /><LoadingState /></>; if (error && !profile) return <><PageHeader title="Mi perfil" /><ErrorState error={error} onRetry={load} /></>; if (!profile) return <EmptyState title="Perfil no disponible" />; return <><PageHeader title="Mi perfil" description="Información personal y de contacto." /><DetailSection title="Información de cuenta"><FormField label="Correo electrónico" value={profile.email} readOnly /><p className="section-copy">Identificador: {profile.id}</p></DetailSection><DetailSection title="Datos personales"><form onSubmit={submit}><FormField label="Nombre completo" {...form.register('full_name')} error={form.formState.errors.full_name?.message} /><FormField label="Teléfono" {...form.register('phone')} error={form.formState.errors.phone?.message} />{profile.address && <FormField label="Dirección" value={profile.address} readOnly />}{profile.commune && <FormField label="Comuna" value={profile.commune} readOnly />}<p className="section-copy">Para actualizar datos no disponibles en este formulario, comunícate con la Municipalidad de Lampa.</p>{error && <ErrorState error={error} />}{saved && <p role="status">Perfil actualizado correctamente.</p>}<button className="button" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? 'Guardando...' : 'Guardar cambios'}</button></form></DetailSection></> }
export const CitizenOirsPage = () => <PublicOirsPage />
