import { EmptyState } from '../feedback';
import { formatDate, getStatusPresentation } from '../../utils/presentation';
export type Column<T> = { key: keyof T; label: string; render?: (value: T[keyof T], row: T) => React.ReactNode };
export function DataTable<T extends { id: number }>({ columns, rows, caption }: { columns: Column<T>[]; rows: T[]; caption?: string }) { if (!rows.length) return <EmptyState />; return <div className="table-wrap"><table>{caption && <caption className="sr-only">{caption}</caption>}<thead><tr>{columns.map((column, index) => <th key={`${String(column.key)}-${index}`} scope="col">{column.label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column, index) => <td key={`${String(column.key)}-${index}`} data-label={column.label}>{column.render ? column.render(row[column.key], row) : String(row[column.key] ?? '')}</td>)}</tr>)}</tbody></table></div>; }
export function Pagination({ page, pages, onChange }: { page: number; pages: number; onChange: (page: number) => void }) { return <nav className="pagination" aria-label="Paginacion"><button disabled={page <= 1} onClick={() => onChange(page - 1)}>Anterior</button><span aria-live="polite">{page} de {pages}</span><button disabled={page >= pages} onClick={() => onChange(page + 1)}>Siguiente</button></nav>; }
export const SearchInput = (props: React.InputHTMLAttributes<HTMLInputElement>) => <input type="search" aria-label="Buscar" placeholder="Buscar" {...props} />;
export const FilterBar = ({ children }: { children: React.ReactNode }) => <div className="filters">{children}</div>;
export const StatusBadge = ({ value }: { value: string }) => { const state = getStatusPresentation(value); return <span className={`badge badge-${state.tone}`}><i className={`bi ${state.icon}`} aria-hidden="true" />{state.label}</span>; };
export const DateCell = ({ value }: { value?: string | null }) => <time dateTime={value || undefined}>{formatDate(value)}</time>;
export const TableActions = ({ children }: { children: React.ReactNode }) => <div className="table-actions">{children}</div>;
