const express = require('express');
const authenticate = require('../../middleware/authentication');
const authorize = require('../../middleware/authorization');
const controller = require('./controller');
const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res)).catch(next);
const router = express.Router();
router.post('/api/v1/documents/:id/approvals', authenticate, authorize('documents.edit'), wrap(controller.request));
router.get('/api/v1/documents/:id/approvals', authenticate, authorize('documents.view'), wrap(controller.list));
router.post('/api/v1/approvals/:id/decision', authenticate, authorize('documents.review'), wrap(controller.decide));
module.exports = router;
