const { transaction } = require('../../database/transaction');
const { query } = require('../../database/pool');
const { AppError } = require('../../shared/errors');
const audit = require('../../shared/audit');
const repository = require('./repository');
function allowed(document, actor) { if (!document) throw new AppError(404, 'DOCUMENT_NOT_FOUND', 'Documento no encontrado'); if (document.confidentiality_level === 'secret' && document.owner_user_id !== actor.id) throw new AppError(403, 'FORBIDDEN', 'No autorizado para este documento'); }
async function request(documentId, data, actor, context) { return transaction(async (client) => { const document = await repository.findDocument(client, documentId, true); allowed(document, actor); if (!document.current_version_id || document.status !== 'draft') throw new AppError(409, 'DOCUMENT_NOT_READY_FOR_APPROVAL', 'El documento debe estar en borrador con versión vigente'); if (await repository.pendingReviews(client, documentId)) throw new AppError(409, 'REVIEWS_PENDING', 'El documento tiene revisiones pendientes'); const userIds = data.approvers.map((item) => item.user_id); const users = await repository.activeUsers(client, userIds); if (users.length !== userIds.length) throw new AppError(400, 'APPROVER_NOT_FOUND', 'Uno o más aprobadores no están activos'); const approvals = await repository.create(client, documentId, actor.id, data.approvers); await repository.setStatus(client, documentId, 'in_approval'); await audit.record(client, { eventName: 'document_approval_requested', moduleCode: 'document_approvals', entityType: 'document', entityId: documentId, actor, ipAddress: context.ip, payload: { approval_ids: approvals.map((item) => item.id), approvers: data.approvers } }); return approvals; }); }
async function decide(approvalId, data, actor, context) { return transaction(async (client) => { const approval = await repository.find(client, approvalId, true); if (!approval) throw new AppError(404, 'APPROVAL_NOT_FOUND', 'Solicitud de aprobación no encontrada');     if (Number(approval.approver_user_id) !== actor.id) throw new AppError(403, 'FORBIDDEN', 'Solo puede decidir el aprobador asignado'); if (approval.status !== 'pending') throw new AppError(409, 'APPROVAL_ALREADY_DECIDED', 'La aprobación ya fue decidida'); if (await repository.priorPending(client, approval.document_id, approval.sequence_order)) throw new AppError(409, 'APPROVAL_SEQUENCE_PENDING', 'Debe resolver las aprobaciones anteriores'); const updated = await repository.decide(client, approvalId, data.decision, data.decision_note); if (data.decision === 'rejected') await repository.setStatus(client, approval.document_id, 'draft'); else if ((await repository.allApproved(client, approval.document_id)).incomplete === 0) await repository.setStatus(client, approval.document_id, 'approved'); await audit.record(client, { eventName: 'document_approval_decided', moduleCode: 'document_approvals', entityType: 'document', entityId: approval.document_id, actor, ipAddress: context.ip, payload: { approval_id: approvalId, decision: data.decision } }); return updated; }); }
async function list(documentId, actor) { const document = await repository.findDocument({ query }, documentId); allowed(document, actor); return repository.list({ query }, documentId); }
module.exports = { request, decide, list };
