import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api/endpoints';
import type { Procedure, PublicCalendarEvent, PublicNews, PublicNotice } from '../api/types';
import { EmptyState, ErrorState, LoadingState } from '../components/feedback';
import { DetailSection, PageHeader } from '../components/domain';
import { DataTable, StatusBadge } from '../components/tables';
import { formatDate, formatDateTime } from '../utils/presentation';

export function HomePage() { return <><PageHeader title="Servicios municipales" description="Acceda a trámites, información pública y canales de atención de la Municipalidad de Lampa." /><section className="public-hero"><div><p className="eyebrow">Atención digital</p><h2>Gestiones claras, cerca de usted.</h2><p>Inicie un trámite, consulte requisitos y realice seguimiento en línea.</p><Link className="button" to="/tramites">Ver tramites disponibles</Link></div><div className="public-hero-links"><Link to="/oirs"><i className="bi bi-chat-square-text" aria-hidden="true" />OIRS</Link><Link to="/login"><i className="bi bi-person-circle" aria-hidden="true" />Ingreso ciudadano</Link></div></section></>; }
export function ProceduresPage() { const [items, setItems] = useState<Procedure[]>([]); const [error, setError] = useState<Error>(); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); useEffect(() => { api.procedures().then(({ data }) => setItems(data)).catch(setError).finally(() => setLoading(false)); }, []); if (error) return <><PageHeader title="Trámites" description="Servicios disponibles para la comunidad." /><ErrorState error={error} /></>; if (loading) return <><PageHeader title="Trámites" description="Servicios disponibles para la comunidad." /><LoadingState /></>; const filtered = items.filter((item) => `${item.title} ${item.department_name || ''}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader title="Trámites" description="Encuentre los requisitos e instrucciones antes de iniciar su solicitud." /><div className="filters"><label className="sr-only" htmlFor="procedure-search">Buscar trámites</label><input id="procedure-search" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre o departamento" /></div>{!filtered.length ? <EmptyState title="No se encontraron trámites" message="Pruebe con otra búsqueda." /> : <DataTable columns={[{ key: 'title', label: 'Trámite', render: (value, row) => <Link to={`/tramites/${row.id}`}>{String(value)}</Link> }, { key: 'department_name', label: 'Departamento' }]} rows={filtered} caption="Trámites disponibles" />}</>; }
export function ProcedureDetailPage() { const { procedureId = '' } = useParams(); const [item, setItem] = useState<Procedure>(); const [error, setError] = useState<Error>(); useEffect(() => { api.procedure(procedureId).then(({ data }) => setItem(data)).catch(setError); }, [procedureId]); if (error) return <><PageHeader title="Trámite" /><ErrorState error={error} /></>; if (!item) return <LoadingState />; return <><PageHeader title={item.title} description={item.department_name} /><div className="page-actions"><Link to="/tramites">Volver a trámites</Link><Link className="button" to={`/portal/requests/new/${item.id}`}>Iniciar solicitud</Link></div><DetailSection title="Instrucciones"><p>{item.instructions || 'No se informaron instrucciones.'}</p></DetailSection><DetailSection title="Requisitos"><div dangerouslySetInnerHTML={{ __html: item.requirements_html || 'No se informaron requisitos.' }} /></DetailSection></>; }
const stripHtml = (value: string) => value.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
export function PublicContentPage({ title }: { title: string }) { if (title === 'Noticias') return <NewsPage />; if (title === 'Avisos') return <NoticesPage />; return <CalendarPage />; }
function NewsPage() { const [items, setItems] = useState<PublicNews[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error>(); useEffect(() => { api.publicContent('news').then((response) => setItems(response.data as PublicNews[])).catch(setError).finally(() => setLoading(false)); }, []); if (loading) return <><PageHeader title="Noticias" description="Novedades e información institucional de la Municipalidad de Lampa." /><LoadingState /></>; if (error) return <><PageHeader title="Noticias" description="Novedades e información institucional de la Municipalidad de Lampa." /><ErrorState error={error} /></>; if (!items.length) return <><PageHeader title="Noticias" description="Novedades e información institucional de la Municipalidad de Lampa." /><EmptyState title="No hay noticias publicadas" message="La Municipalidad de Lampa aún no ha publicado noticias disponibles." /></>; return <><PageHeader title="Noticias" description="Novedades e información institucional de la Municipalidad de Lampa." /><section className="public-card-grid">{items.map((item) => <article className="public-card" key={item.id}><span className="public-kicker"><i className="bi bi-megaphone" aria-hidden="true" />Institucional</span><h2>{item.title}</h2>{item.summary && <p>{item.summary}</p>}<time dateTime={item.published_at}>{formatDate(item.published_at)}</time></article>)}</section></>; }
function NoticesPage() { const [items, setItems] = useState<PublicNotice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error>(); useEffect(() => { api.publicContent('notices').then((response) => setItems(response.data as PublicNotice[])).catch(setError).finally(() => setLoading(false)); }, []); if (loading) return <><PageHeader title="Avisos" description="Comunicados municipales vigentes." /><LoadingState /></>; if (error) return <><PageHeader title="Avisos" description="Comunicados municipales vigentes." /><ErrorState error={error} /></>; if (!items.length) return <><PageHeader title="Avisos" description="Comunicados municipales vigentes." /><EmptyState title="No hay avisos vigentes" message="Actualmente no existen avisos municipales dentro de su período de vigencia." /></>; return <><PageHeader title="Avisos" description="Comunicados municipales vigentes." /><section className="public-notice-list">{items.map((item) => <article className="public-notice" key={item.id}><div><StatusBadge value={item.notice_type} /><h2>{item.title}</h2><p>{stripHtml(item.body_html)}</p></div><p className="public-meta"><i className="bi bi-calendar-range" aria-hidden="true" />Vigencia: {formatDate(item.start_at)} a {formatDate(item.end_at)}</p></article>)}</section></>; }
function CalendarPage() { const [items, setItems] = useState<PublicCalendarEvent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error>(); useEffect(() => { api.publicContent('calendar').then((response) => setItems(response.data as PublicCalendarEvent[])).catch(setError).finally(() => setLoading(false)); }, []); if (loading) return <><PageHeader title="Calendario" description="Actividades e hitos municipales." /><LoadingState /></>; if (error) return <><PageHeader title="Calendario" description="Actividades e hitos municipales." /><ErrorState error={error} /></>; if (!items.length) return <><PageHeader title="Calendario" description="Actividades e hitos municipales." /><EmptyState title="No hay actividades programadas" message="Actualmente no existen actividades públicas próximas." /></>; return <><PageHeader title="Calendario" description="Actividades e hitos municipales." /><ol className="public-timeline">{items.map((item) => <li key={item.id}><time dateTime={item.start_at}><strong>{formatDate(item.start_at)}</strong><span>{formatDateTime(item.start_at)}</span></time><article><StatusBadge value={item.status} /><h2>{item.title}</h2>{item.description && <p>{item.description}</p>}{item.location && <p className="public-meta"><i className="bi bi-geo-alt" aria-hidden="true" />{item.location}</p>}{item.end_at && <p className="public-meta">Finaliza: {formatDateTime(item.end_at)}</p>}</article></li>)}</ol></>; }
