import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api/endpoints';
import type { Procedure } from '../api/types';
import { ErrorState, LoadingState } from '../components/feedback';
import { DetailSection, PageHeader } from '../components/domain';
import { DataTable } from '../components/tables';
export function HomePage() { return <><PageHeader title="Servicios municipales" description="Gestion documental y tramites en linea."/><Link className="button" to="/tramites">Ver tramites disponibles</Link></>; }
export function ProceduresPage() { const [items,setItems] = useState<Procedure[]>([]); const [error,setError] = useState<Error>(); useEffect(() => { api.procedures().then(({data}) => setItems(data)).catch(setError); }, []); if (error) return <ErrorState error={error}/>; if (!items.length) return <LoadingState/>; return <><PageHeader title="Tramites"/><DataTable columns={[{key:'title',label:'Tramite',render:(value,row) => <Link to={`/tramites/${row.id}`}>{String(value)}</Link>},{key:'department_name',label:'Departamento'}]} rows={items}/></>; }
export function ProcedureDetailPage() { const { procedureId = '' } = useParams(); const [item,setItem] = useState<Procedure>(); const [error,setError] = useState<Error>(); useEffect(() => { api.procedure(procedureId).then(({data}) => setItem(data)).catch(setError); }, [procedureId]); if (error) return <ErrorState error={error}/>; if (!item) return <LoadingState/>; return <><PageHeader title={item.title} description={item.department_name}/><DetailSection title="Instrucciones"><p>{item.instructions}</p></DetailSection><DetailSection title="Requisitos"><div dangerouslySetInnerHTML={{ __html: item.requirements_html || 'No se informaron requisitos.' }}/></DetailSection><Link className="button" to={`/portal/requests/new/${item.id}`}>Iniciar solicitud</Link></>; }
export function PublicContentPage({ title }: { title: string }) { const kind = title === 'Noticias' ? 'news' : title === 'Avisos' ? 'notices' : 'calendar'; const [data, setData] = useState<unknown>(); const [error, setError] = useState<Error>(); useEffect(() => { api.publicContent(kind).then(({ data: response }) => setData(response)).catch(setError); }, [kind]); if (error) return <ErrorState error={error}/>; if (!data) return <LoadingState/>; return <><PageHeader title={title}/><pre>{JSON.stringify(data, null, 2)}</pre></>; }
